export const countries = [
  { name: 'India', code: 'IND', amount: 'Rs' },
  { name: 'America', code: 'US', amount: '$' },
  { name: 'Saudhi Arabia', code: 'SAU', amount: 'AED' },
  { name: 'srilanka', code: 'SA', amount: 'Rs' },
];

export const states = [
  {
    id: 1,
    name: 'AndraPradesh',
    districts: [
      'Anantapur',
      'Chittoor',
      'East Godavari',
      'Guntur',
      'Kadapa',
      'Krishna',
      'Kurnool',
      'Prakasam',
      'Nellore',
      'Srikakulam',
      'Visakhapatnam',
      'Vizianagaram',
      'West Godavari',
    ],
  },
  {
    id: 2,
    name: 'ArunachalPradesh',
    districts: [
      'Anjaw',
      'Changlang',
      'Dibang Valley',
      'East Kameng',
      'East Siang',
      'Kra Daadi',
      'Kurung Kumey',
      'Lohit',
      'Longding',
      'Lower Dibang Valley',
      'Lower Subansiri',
      'Namsai',
      'Papum Pare',
      'Siang',
      'Tawang',
      'Tirap',
      'Upper Siang',
      'Upper Subansiri',
      'West Kameng',
      'West Siang',
      'Itanagar',
    ],
  },
  { id: 3, name: 'Goa', districts: ['North Goa', 'South Goa'] },
  {
    id: 4,
    name: 'Telangana',
    districts: [
      'Adilabad',
      'Bhadradri Kothagudem',
      'Hyderabad',
      'Jagtial',
      'Jangaon',
      'Jayashankar',
      'Jogulamba',
      'Kamareddy',
      'Karimnagar',
      'Khammam',
      'Komaram Bheem',
      'Mahabubabad',
      'Mahbubnagar',
      'Mancherial',
      'Medak',
      'Medchal',
      'Nagarkurnool',
      'Nalgonda',
      'Nirmal',
      'Nizamabad',
      'Peddapalli',
      'Rajanna Sircilla',
      'Ranga Reddy',
      'Sangareddy',
      'Siddipet',
      'Suryapet',
      'Vikarabad',
      'Wanaparthy',
      'Warangal Rural',
      'Warangal Urban',
      'Yadadri Bhuvanagiri',
    ],
  },
  {
    id: 5,
    name: 'Delhi',
    districts: [
      'Central Delhi',
      'East Delhi',
      'New Delhi',
      'North Delhi',
      'North East Delhi',
      'North West Delhi',
      'Shahdara',
      'South Delhi',
      'South East Delhi',
      'South West Delhi',
      'West Delhi',
    ],
  },
];
